import { compare, invalid, toIpa } from './write';
// @ts-ignore
import { replaceEach } from 'https://sumi.space/js/string.js';

export const acronymToWord = (acronym: string) =>
  replaceEach(acronym.toUpperCase(), [
    [/[AIUEO]/g, (it) => 'h' + it.toLowerCase()],
    [/[NMCDBKTPXSFZRL]/g, (it) => it.toLowerCase() + 'a'],
    [/J/g, 'je'],
    [/V/g, 'vo'],
    [/G/g, 'nu'],
    [/H/g, 'xu'],
    [/Q/g, 'ku'],
    [/W/g, 'vi'],

    [/Ä|Æ/g, 'ja'],
    [/Ǝ/g, 've'],
    [/Ö|Œ|Ø/g, 'jo'],
    [/Y|Ü/g, 'ju'],
  ]);

enum Klass {
  Preposition = '前置詞',
  Preverb = '前助動詞',
  Postverb = '後助動詞',
  Verb = '動詞',
  Numeral = '數詞',
  Joiner = '接續詞',
  Other = '助詞',
}

export enum Formation {
  Simplex,
  Complex,
  Idiom,
}

interface ValuePre {
  d: string;
  c: Klass;
  en: string;
  ja?: string;
  formation: Formation;
  o: string;
  token?: string;
  complex?: string[];
  idiom?: string[];
}

/*
proto indo european
*ḱ   x
*k   k
*kʷ  k
*bʰ  b
*dʰ  d
*ǵʰ  j
*gʰ  c
*gʷʰ c
*/

/*
- animate - subject, inanimate, object
- one thing - subject, many things - object
*/

const dicPre = new Map<string, ValuePre>(
  Object.entries({
    by: {
      d: '2024-02-13',
      c: Klass.Preposition,
      en: 'nominative',
      ja: '主格。…が',
      o: 'https://en.wiktionary.org/wiki/bi#Old_English',
      token: 'bi',
    },
    because: {
      d: '2025-07-15',
      c: Klass.Preposition,
      en: 'causative',
      ja: '因格。…に因って',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fram',
      token: 'fo',
    },
    him: {
      d: '2024-02-13',
      c: Klass.Preposition,
      en: 'accusative',
      ja: '對格。…を',
      o: 'https://en.wiktionary.org/wiki/den#German',
      token: 're',
    },
    to: {
      d: '2024-02-13',
      c: Klass.Preposition,
      en: 'dative',
      ja: '與格。…へ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/t%C5%8D',
      token: 'to',
    },
    with: {
      d: '2024-12-24',
      c: Klass.Preposition,
      en: 'comitative',
      ja: '共格。…が關はって',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/midi',
      token: 'mi',
    },
    ly: {
      d: '2024-02-13',
      c: Klass.Preposition,
      en: 'recursive',
      ja: '己格。この文自身が指す事象を…として',
      o: 'a priori',
      token: 'xo',
    },

    done: {
      d: '2024-02-13',
      c: Klass.Preverb,
      en: 'passive. foregoeth a preposition and a verb and make an apposition ',
      ja: '受動態。前置詞と動詞に前置し動詞の同格を前置詞に對應する格に一致させる。對格前置詞は省略しても良い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ga-',
      token: 'ca',
    },
    so: {
      d: '2024-02-13',
      c: Klass.Preverb,
      en: 'which is, so, of course (non-restrictive)',
      ja: '非制限修飾。當然に…である',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/þus',
      token: 'dus',
    },

    did: {
      d: '2024-02-13',
      c: Klass.Postverb,
      en: 'realis past',
      ja: '叙實 過去',
      token: '-a',
    },
    do: {
      d: '2024-02-13',
      c: Klass.Postverb,
      en: 'realis present',
      ja: '叙實 現在',
      token: '-i',
    },
    will: {
      d: '2024-02-13',
      c: Klass.Postverb,
      en: 'realis future',
      ja: '叙實 未來',
      token: '-u',
    },
    if_be: {
      d: '2025-07-19',
      c: Klass.Postverb,
      en: 'realis nominal',
      ja: '叙想 不變',
      token: '-en',
    },
    if_did: {
      d: '2025-05-27',
      c: Klass.Postverb,
      en: 'irrealis past',
      ja: '叙想 過去',
      token: '-an',
    },
    if_do: {
      d: '2025-05-27',
      c: Klass.Postverb,
      en: 'irrealis present',
      ja: '叙想 現在',
      token: '-in',
    },
    if_will: {
      d: '2025-05-27',
      c: Klass.Postverb,
      en: 'irrealis future',
      ja: '叙想 未來',
      token: '-un',
    },

    begin: {
      d: '2024-05-26',
      c: Klass.Verb,
      en: 'begin',
      ja: '起動相。…し始める',
      etymology:
        'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ginnan%C4%85',
      token: 'ci',
    },
    end: {
      d: '2024-05-26',
      c: Klass.Verb,
      en: 'end',
      ja: '終了相。…し終へる',
      etymology: 'https://en.wiktionary.org/wiki/finis#Latin',
      token: 'fi',
    },

    which: {
      d: '2024-02-13',
      c: Klass.Other,
      en: 'followeth a verb and opens a local scope',
      ja: '動詞に後置して局所視野を開く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hw%C4%AB',
      token: 'vi',
    },
    whether: {
      d: '2024-07-28',
      c: Klass.Other,
      en: 'truthfulness clause. @n is whether ...',
      ja: '文に先立って程度に變換する。@nは…かどうかである',
      o: 'https://en.wiktionary.org/wiki/si#Latin',
      token: 'si',
    },
    _close: {
      d: '2024-02-13',
      c: Klass.Other,
      en: 'closeth clause',
      ja: '構造を閉ぢる。非曖昧な時に省略する',
      o: 'https://en.wiktionary.org/wiki/啦#Chinese',
      token: 'ru',
    },

    then: {
      d: '2025-06-11',
      c: Klass.Other,
      en: 'when, at the same time',
      ja: '以降。それから。さうして',
      token: 'ku',
    },

    and: {
      d: '2024-02-13',
      c: Klass.Joiner,
      en: 'and, all, conjunction',
      ja: '連言。かつ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bai',
      token: 'pse',
    },
    or: {
      d: '2024-02-13',
      c: Klass.Joiner,
      en: 'or, at least one, disjunction',
      ja: '選言。または',
      token: 'pso',
    },
    iff: {
      d: '2024-02-13',
      c: Klass.Joiner,
      en: 'if and only iff, equivalence',
      ja: '同値。即ち',
      token: 'psa',
    },
    xor: {
      d: '2025-01-02',
      c: Klass.Joiner,
      en: 'either',
      ja: '排他的選言。いづれか',
      idiom: ['zero', 'iff'],
    },

    called: {
      d: '2024-02-13',
      c: Klass.Other,
      en: '@n is called ...',
      ja: '呼稱を動詞化する。@nは…と呼ばれる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/namô',
      token: 'ne',
    },

    _var: {
      d: '2025-02-27',
      c: Klass.Other,
      en: 'bound variable',
      ja: '變項選言と本文を區切る',
      token: 'zo',
    },

    zero: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '0',
      ja: '0',
      o: 'https://en.wiktionary.org/wiki/%D8%B5%D9%81%D8%B1#Arabic',
      token: 'zi',
    },
    one: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '1',
      ja: '1',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Indo-Iranian/Háykas',
      token: 'ka',
    },
    two: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '2',
      ja: '2',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/twai',
      token: 'tu',
    },
    three: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '3',
      ja: '3',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEr%C4%ABz',
      token: 'di',
    },
    four: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '4',
      ja: '4',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fedw%C5%8Dr',
      token: 'fir',
    },
    five: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '5',
      ja: '5',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Indo-Iranian/p%C3%A1n%C4%8Da',
      token: 'pan',
    },
    six: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '6',
      ja: '6',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Indo-Iranian/%C5%A1w%C3%A1%C4%87%C5%A1',
      token: 'xek',
    },
    seven: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '7',
      ja: '7',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sebun',
      token: 'sep',
    },
    eight: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '8',
      ja: '8',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/aht%C5%8Du',
      token: 'vak',
    },
    nine: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '9',
      ja: '9',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/newun',
      token: 'nin',
    },

    decimal: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'decimal separator',
      ja: '小數點',
      o: 'https://en.wiktionary.org/wiki/pungo#Latin',
      token: 'pu',
    },
    kilo: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: '1000. 3-digit separator',
      ja: '1000。3桁ごとの區切り',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BE%C5%ABsund%C4%AB',
      token: 'ki',
    },

    infinite: {
      d: '2024-09-06',
      c: Klass.Numeral,
      en: '(countable or uncountable) infinite',
      ja: '（加算または非可算の）無限',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sin-',
      token: 'sin',
    },

    how_many: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'how many?',
      ja: '数量疑問。幾つ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hw%C5%8D',
      token: 'vo',
    },

    each: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'each, every, all',
      ja: '各。全',
      o: 'https://en.wiktionary.org/wiki/%CF%80%E1%BE%B6%CF%82#Ancient_Greek',
      token: 'pa',
    },

    at_most: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'at most. ≤',
      ja: '最大…。≤',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/l%C4%ABtilaz',
      token: 'li',
    },
    less_than: {
      d: '2024-08-31',
      c: Klass.Numeral,
      en: 'less than. <',
      ja: '…未満。<',
      o: 'https://en.wiktionary.org/wiki/l%C3%A6s#Etymology_2_2',
      token: 'ra',
    },

    plural: {
      d: '2024-09-17',
      c: Klass.Numeral,
      en: 'plural, at least two',
      ja: '複數。2以上',
      idiom: ['two', 'at_most'],
    },

    _add: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'addition. +',
      ja: '加算。+',
      o: 'https://en.wiktionary.org/wiki/%D8%AC%D9%85%D8%B9',
      token: 'jam',
    },
    _sub: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'subtraction. -',
      ja: '減算。-',
      o: 'https://en.wiktionary.org/wiki/%D8%B7%D8%B1%D8%AD',
      token: 'tar',
    },
    _mul: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'multiplication. ×',
      ja: '乘算, ×',
      o: 'https://en.wiktionary.org/wiki/%D8%B6%D8%B1%D8%A8',
      token: 'drap',
    },
    _div: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'division. /',
      ja: '除算。/',
      o: 'https://en.wiktionary.org/wiki/%D9%82%D8%B3%D9%85#Arabic',
      token: 'ksam',
    },
    _mod: {
      d: '2024-08-24',
      c: Klass.Numeral,
      en: 'modulo',
      ja: '剩餘',
      o: 'https://en.wiktionary.org/wiki/modulus#Latin',
      token: 'mot',
    },
    _exp: {
      d: '2024-08-24',
      c: Klass.Numeral,
      en: 'exponentiation',
      ja: '冪乘',
      o: 'https://en.wiktionary.org/wiki/potere#Latin',
      token: 'pot',
    },
    _log: {
      d: '2024-08-24',
      c: Klass.Numeral,
      en: 'logarithm',
      ja: '對數',
      o: 'https://en.wiktionary.org/wiki/logarithmo#Latin',
      token: 'lok',
    },

    th: {
      d: '2024-08-02',
      c: Klass.Other,
      en: '@n is …-th',
      ja: '數に先立つ。@nは第…',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/-i%C3%BE%C5%8D',
      token: 'do',
    },
    of: {
      d: '2024-08-02',
      c: Klass.Other,
      en: '@n are … individuals',
      ja: '數に先立つ。@nは…個',
      o: 'https://en.wiktionary.org/wiki/%E5%80%8B',
      token: 'co',
    },

    first: {
      d: '2024-09-14',
      c: Klass.Verb,
      en: '@n is 0th(, first, primary)',
      ja: '@nは最初、第0',
      idiom: ['th', 'zero'],
    },
    second: {
      d: '2024-09-14',
      c: Klass.Verb,
      en: '@n is 1st(, second, other)',
      ja: '@nは第1',
      idiom: ['th', 'one'],
    },
    last: {
      d: '2024-09-14',
      c: Klass.Verb,
      en: '@n is last(, final)',
      ja: '@nは最終',
      idiom: ['th', 'each'],
    },

    i: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is me',
      ja: '@nは我',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mek',
      token: 'je',
    },
    thou: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is thee',
      ja: '@nは汝',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEek',
      token: 'de',
    },
    he: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is (him, it, this, that, the definite entity)',
      ja: '@nは彼、あれ、それ、これ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hiz',
      token: 'xe',
    },
    self: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is oneself',
      ja: '@nは己',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sek',
      token: 'ze',
    },
    who: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is who',
      ja: '@nは誰、何',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hwaz',
      token: 've',
    },

    this: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is this',
      ja: '@nは これ',
      idiom: ['he', 'near'],
    },
    yon: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is that',
      ja: '@nは あれ',
      idiom: ['he', 'far'],
    },

    level: {
      d: '2024-09-29',
      c: Klass.Numeral,
      en: 'normal, moderate, default, usual, ordinary',
      ja: '普通、標準',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/gamet',
      token: 'mu',
    },
    least: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'least, smallest, lowest',
      ja: '最少量',
      token: 'faj',
    },
    little: {
      d: '2024-09-29',
      c: Klass.Numeral,
      en: 'little, small, low',
      ja: '少量',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fawaz',
      token: 'fa',
    },
    much: {
      d: '2024-09-29',
      c: Klass.Numeral,
      en: 'much, great, high',
      ja: '多量',
      o: 'https://en.wiktionary.org/wiki/hoch#German',
      token: 'ho',
    },
    most: {
      d: '2024-02-13',
      c: Klass.Numeral,
      en: 'most, greatest, highest',
      ja: '最多量',
      token: 'hoj',
    },
    down: {
      d: '2024-09-29',
      c: Klass.Numeral,
      en: 'down, decreasing',
      ja: '減少量',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fallan%C4%85',
      token: 'do',
    },
    up: {
      d: '2024-09-29',
      c: Klass.Numeral,
      en: 'up, increasing',
      ja: '增加量',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/r%C4%ABsan%C4%85',
      token: 'ri',
    },

    _self: {
      d: '2024-02-17',
      c: Klass.Verb,
      en: '@n is the language',
      ja: '@nは この言語',
      token: 'kxal',
    },

    // content words

    deny: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n contradicteth (negateth, denieth) @a',
      ja: '@nは@aを否定（に矛盾）する',
      o: 'https://en.wiktionary.org/wiki/neque#Latin',
      token: 'nek',
    },
    back: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n is temporally inverse (opposite, reversed) of @a',
      ja: '@nは@aの逆行',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bak%C4%85',
      token: 'bak',
    },
    counter: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n complementeth (is dual of) @a',
      ja: '@nは@aを補完する（の雙對）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/an%C3%BEeraz',
      token: 'an',
    },
    relate: {
      d: '2024-09-14',
      c: Klass.Verb,
      en: '@n is related to @a (@a-ish)',
      ja: '@nは@aに關はる（@a的）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kin%C3%BEiz',
      token: 'kint',
    },
    happen: {
      d: '2024-08-23',
      c: Klass.Verb,
      en: '@n existeth (happeneth, occureth, realiseth, is actual)',
      ja: '@nは存在する（起こる、實現する、實際である）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skehan%C4%85',
      token: 'xeh',
    },
    make: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n maketh (buildeth, createth) @a from @g (material, component)',
      ja: '@nは@a（材料、部品）から@d（完成品）を作る（構成する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/mak%C5%8Dn',
      token: 'mak',
    },
    break: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n breaketh (destructeth) @a into @d (pieces, components)',
      ja: '@nは@aを@d（部品）へ壞す（分解する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/brekan%C4%85',
      token: 'brek',
      complex: ['back', 'make'],
    },

    have: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n hath (owneth) @a (property)',
      ja: '@nは@aを有する（保持する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/habjan%C4%85',
      token: 'hap',
    },
    give: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n giveth @a to @d',
      ja: '@nは@aを@dへ與ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/geban%C4%85',
      token: 'cep',
    },
    take: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n taketh (receiveth) @a from @g',
      ja: '@nは@aを@gから受く（得る）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/neman%C4%85',
      token: 'nem',
      complex: ['back', 'give'],
    },

    come: {
      d: '2024-08-26',
      c: Klass.Verb,
      en: '@n is (cometh) from (since) @a (source, origin, start)',
      ja: '@nは@a（始點、起源、由來）から來る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kweman%C4%85',
      token: 'kem',
    },
    go: {
      d: '2024-08-26',
      c: Klass.Verb,
      en: '@n is (goeth) to (until) @a (sink, destination, goal)',
      ja: '@nは@a（終點、到達點）へ往く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/g%C4%81n%C4%85',
      token: 'can',
    },
    pass: {
      d: '2024-08-26',
      c: Klass.Verb,
      en: '@n is (passeth) through (via) @a (process, route, medium)',
      ja: '@nは@a（通過點、途中、媒體）を通る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEurhw',
      token: 'dur',
    },
    stay: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is (stayeth) at @a (position, location, place)',
      ja: '@nは@a（地點、時點）に有る（存在する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/l%C4%ABban%C4%85',
      token: 'lip',
    },

    element: {
      d: '2024-08-06',
      c: Klass.Verb,
      en: '@n is in @{a:collection, set, group, list}',
      ja: '@nは@a（群、集合、列擧）に屬する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/gad',
      token: 'cat',
    },
    part: {
      d: '2024-08-06',
      c: Klass.Verb,
      en: '@n is (part, component) of @{a:whole}',
      ja: '@nは@a（全體）の部分',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/dailiz',
      token: 'del',
    },
    complex: {
      d: '2024-08-25',
      c: Klass.Verb,
      en: '@n is complex (consisteth of many parts)',
      ja: '@nは複雜（部分が多い）',
      complex: ['done', 'part', 'much'],
    },
    simple: {
      d: '2024-08-25',
      c: Klass.Verb,
      en: '@n (is simple, consisteth of few parts)',
      ja: '@nは單純（部分が少ない）',
      complex: ['done', 'part', 'little'],
    },
    atom: {
      d: '2024-08-25',
      c: Klass.Verb,
      en: '@n is an atom',
      ja: '@nは原子（單位）',
      complex: ['done', 'part', 'least'],
    },

    contain: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n is containeth @{1:within}',
      ja: '@nは@aを内側に持つ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/l%C5%ABkan',
      token: 'luk',
    },
    full: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n is full of @a',
      ja: '@nは@aに滿ちる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fullaz',
      idiom: ['most', 'contain'],
      token: 'fol',
    },
    empty: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n is empty of @a',
      ja: '@nは@aを缺く（空）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/t%C5%8Dmaz',
      idiom: ['least', 'contain'],
      token: 'tom',
    },

    move: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n moveth (is dynamic)',
      ja: '@nは動く（變動する、動的）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wegan%C4%85',
      token: 'vex',
    },
    stop: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n (stopeth, halteth, is static)',
      ja: '@nは止まる（停止する、静的）',
      idiom: ['least', 'move'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/stopp%C5%8Dn',
      token: 'stop',
    },

    point: {
      d: '2024-10-01',
      c: Klass.Verb,
      en: '@n is a (point, position, dot)',
      ja: '@nは點（位置）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bruzdaz',
      token: 'brut',
    },
    interval: {
      d: '2024-10-01',
      c: Klass.Verb,
      en: '@n is (an interval, an area, a volume, a domain)',
      ja: '@nは區間（容積、領域）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/braidaz',
      token: 'bret',
    },

    world: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a (world, universe)',
      ja: '@nは世界（宇宙、時空間）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/haimaz',
      token: 'xem',
    },
    space: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is the 3-dimensional physical spacial continuum',
      ja: '@nは3次元物理的空間',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/r%C5%ABm%C4%85',
      token: 'rum',
    },
    time: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is the 1-dimensional physical temporal continuum',
      ja: '@nは1次元物理的時間',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/t%C4%ABm%C3%B4',
      token: 'tim',
    },
    thing: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a (thing, matter) located in a spacetime',
      ja: '@nは物理的存在物（物體）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEing%C4%85',
      token: 'dink',
    },
    mass: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n is mass of @a',
      ja: '@nの質量は@a',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/balk%C3%B4',
      token: 'balx',
    },

    energy: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n is energy of @a',
      ja: '@nの能源は@a',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Italic/gn%C4%81wos',
      token: 'nav',
    },
    heat: {
      d: '2024-09-06',
      c: Klass.Verb,
      en: '@n is heat in @a',
      ja: '@nの熱量は@a',
      complex: ['hot', 'energy'],
    },
    electric: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n hath electric charge in @a',
      ja: '@nの電荷は@a',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sparkaz',
      token: 'spak',
    },
    force: {
      d: '2024-10-01',
      c: Klass.Verb,
      en: '@n is force',
      ja: '@nは力',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wald%C4%85',
      token: 'vaut',
    },

    wave: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n (medium) waveth @a (form)',
      ja: '@n（媒體）の波は@a（形狀）を成す',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bulgij%C5%8D',
      token: 'bux',
    },
    light: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is (a light, an electromagnetic wave)',
      ja: '@nは光（電磁波）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/leuht%C4%85',
      token: 'lit',
    },
    sound: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is a sound',
      ja: '@nは音',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/klingan%C4%85',
      token: 'klin',
    },
    turn: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n (turneth, rotateth, spineth) around @a (pivot, center)',
      ja: '@nは@a（中心、軸）を回る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEr%C4%93an%C4%85',
      token: 'dren',
    },

    burn: {
      d: '2024-12-08',
      c: Klass.Verb,
      en: '@n (fuel) burneth with @a (oxidant)',
      ja: '@n（燃料）は@a（酸化劑）で燃焼する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/brandaz',
      token: 'bran',
    },

    big: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is big (great)',
      ja: '@nは大きい',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/grautaz',
      token: 'crot',
    },
    small: {
      d: '2024-09-26',
      c: Klass.Verb,
      en: '@n is small',
      ja: '@nは小さい',
      idiom: ['little', 'big'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/smalaz',
      token: 'smal',
    },
    long: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is long',
      ja: '@nは長い（一次元方向に大きく他次元方向に小さい）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/langaz',
      token: 'lank',
    },
    short: {
      d: '2024-09-26',
      c: Klass.Verb,
      en: '@n is short',
      ja: '@nは短い',
      idiom: ['little', 'long'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skurtaz',
      token: 'xurt',
    },
    thick: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is thick',
      ja: '@nは厚い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEekuz',
      token: 'dek',
    },
    thin: {
      d: '2025-07-17',
      c: Klass.Verb,
      en: '@n is thin',
      ja: '@nは薄い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEunnuz',
      idiom: ['little', 'thick'],
      token: 'dun',
    },
    sharp: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n is sharp',
      ja: '@nは鋭い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skarpaz',
      token: 'xarp',
    },
    heavy: {
      d: '2024-07-14',
      c: Klass.Verb,
      en: '@n is heavy',
      ja: '@nは重い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sw%C4%93raz',
      token: 'suar',
    },
    dense: {
      d: '2024-07-15',
      c: Klass.Verb,
      ja: '@n is dense',
      en: '@nは濃い（密集する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEinhtaz',
      token: 'dint',
    },
    swift: {
      d: '2024-06-18',
      c: Klass.Verb,
      en: '@n is (swift, quick)',
      ja: '@nは速い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/snellaz',
      token: 'snel',
    },
    slow: {
      d: '2024-09-06',
      c: Klass.Verb,
      en: '@n is slow',
      ja: '@nは遅い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/slaiwaz',
      token: 'slev',
      idiom: ['little', 'swift'],
    },
    rough: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n (is rough, is coarse, hath much friction) against @a',
      ja: '@nは@aに對して粗い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/r%C5%ABhaz',
      token: 'ruh',
    },
    smooth: {
      d: '2024-09-26',
      c: Klass.Verb,
      en: '@n (is smooth, is sleek, hath little friction) against @a',
      ja: '@nは@aに對して滑らか',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sl%C4%ABkan%C4%85',
      token: 'slik',
      idiom: ['little', 'rough'],
    },
    soft: {
      d: '2024-09-26',
      c: Klass.Verb,
      en: '@n is soft against @a',
      ja: '@nは@aに對して軟らかい',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/w%C4%ABkwan%C4%85',
      token: 'vik',
    },
    hard: {
      d: '2024-09-26',
      c: Klass.Verb,
      en: '@n is hard (firm) against @a',
      ja: '@nは@aに對して軟らかい',
      idiom: ['little', 'soft'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fastuz',
      token: 'fast',
    },
    hot: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n is hot (warm)',
      ja: '@nは熱い（暑い、温かい）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/warmaz',
      token: 'varm',
    },
    cold: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n cold (cool)',
      ja: '@nは冷たい（寒い、涼しい）',
      idiom: ['little', 'hot'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kalan%C4%85',
      token: 'kal',
    },
    far: {
      d: '2024-08-08',
      c: Klass.Verb,
      en: '@n is far (distant, remote) from @a',
      ja: '@nは@aから遠い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ferrai',
      token: 'fer',
    },
    near: {
      d: '2024-08-08',
      c: Klass.Verb,
      en: '@n is near (close to) @a',
      ja: '@nは@aへ近い',
      idiom: ['little', 'far'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/n%C4%93hwaz',
      token: 'nex',
    },
    contact: {
      d: '2024-08-08',
      c: Klass.Verb,
      en: '@n toucheth (is adjacent, is in contact with) @a',
      ja: '@nは@aに接する',
      idiom: ['least', 'far'],
    },

    before: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is before @a in time',
      ja: '@nは@aの過去に有る（時間方向で小さい）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/furai',
      token: 'for',
    },
    below: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is below @a (closer to center of gravity)',
      ja: '@nは@aより下に有る（重心へ近い）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ni%C3%BEan%C4%93',
      token: 'nit',
    },
    hind: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is behind @a',
      ja: '@nは@aの後（進行方向の逆）に有る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hinder',
      token: 'xin',
    },
    front: {
      d: '2025-02-07',
      c: Klass.Verb,
      en: '@n is in front of @a',
      ja: '@nは@aの前（進行方向）に有る',
      idiom: ['done', 'hind'],
    },
    left: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is to the left of @a',
      ja: '@nは@aの左に有る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Old_High_German/link',
      token: 'link',
    },
    right: {
      d: '2025-02-07',
      c: Klass.Verb,
      en: '@n is to the right of @a',
      ja: '@nは@aの右に有る',
      idiom: ['done', 'left'],
    },
    west: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n is to the west of @a',
      ja: '@nは@aの西（自轉方向の逆）に有る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/westraz',
      token: 'vest',
    },
    east: {
      d: '2025-03-01',
      c: Klass.Verb,
      en: '@n is to the east of @a',
      ja: '@nは@aの東（自轉方向）に有る',
      idiom: ['done', 'west'],
    },
    north: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n is to the north of @a',
      ja: '@nは@aより北（反時計回りする極點）へ近い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/nur%C3%BEraz',
      token: 'nurt',
    },
    south: {
      d: '2025-03-01',
      c: Klass.Verb,
      en: '@n is to the south of @a',
      ja: '@nは@aよりの南（時計回りする極點）へ近い',
      idiom: ['done', 'north'],
    },

    solid: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is solid',
      ja: '@nは個體',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/st%C4%ABfaz',
      token: 'stif',
    },
    liquid: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is liquid',
      ja: '@nは液體',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/flut%C4%85',
      token: 'flut',
    },
    gas: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is gas',
      ja: '@nは氣體',
      o: 'https://en.wiktionary.org/wiki/gas#Dutch',
      token: 'cas',
    },
    plasm: {
      d: '2024-07-15',
      c: Klass.Verb,
      en: '@n is plasm',
      ja: '@nは電漿',
      o: 'https://en.wiktionary.org/wiki/flamma#Latin',
      token: 'flam',
    },

    water: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is water (H₂O)',
      ja: '@nは水（H₂O）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wat%C5%8Dr',
      token: 'vat',
    },
    salt: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is salt (NaCl)',
      ja: '@nは鹽（NaCl）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/salt%C4%85',
      token: 'salt',
    },
    stone: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is stone (rock, mineral)',
      ja: '@nは石（巖、鑛物）',
      o: 'https://en.wiktionary.org/wiki/%CE%BC%CE%AD%CF%84%CE%B1%CE%BB%CE%BB%CE%BF%CE%BD#Ancient_Greek',
      token: 'sten',
    },
    metal: {
      d: '2025-07-17',
      c: Klass.Verb,
      en: '@n is metal',
      ja: '@nは金屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stainaz',
      token: 'met',
    },
    smoke: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is smoke (solid or liquid particles in gas)',
      ja: '@nは煙（氣體中の固體または液體の粒子）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/dwemr%C4%85',
      token: 'duim',
    },
    ash: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is ash',
      ja: '@nは灰',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ask%C7%AD',
      token: 'ax',
    },

    wet: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is wet (moist)',
      ja: '@nは濕る（潤う）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/w%C4%93taz',
      complex: ['contain', 'water'],
    },
    dry: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is dry',
      ja: '@nは乾く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/druknaz',
      token: 'drux',
      idiom: ['little', 'wet'],
    },

    colour: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n emiteth @a (colour)',
      ja: '@nは@a（色）を發する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/farwaz',
      token: 'farv',
    },
    hue: {
      d: '2024-11-20',
      c: Klass.Verb,
      en: '@n emiteth (hue, frequency of light) @a',
      ja: '@nは@a（色相）を發する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hiwj%C4%85',
      token: 'xiv',
    },
    red: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is red',
      ja: '@nは赤い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/raudaz',
      token: 'rot',
    },
    orange: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is orange',
      ja: '@nは橙色を呈する',
      o: 'https://en.wiktionary.org/wiki/%D9%86%D8%A7%D8%B1%D9%86%DA%AF#Persian',
      token: 'nar',
    },
    yellow: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is yellow',
      ja: '@nは黃色を呈する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gulaz',
      token: 'cul',
    },
    green: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is green',
      ja: '@nは綠色を呈する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gr%C5%8Dniz',
      token: 'cron',
    },
    blue: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is blue',
      ja: '@nは青い',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bl%C4%93waz',
      token: 'blev',
    },
    purple: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is purple',
      ja: '@nは紫色を呈する',
      o: 'https://en.wiktionary.org/wiki/%E1%BC%B4%CE%BF%CE%BD#Ancient_Greek',
      token: 'viun',
    },
    vivid: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is vivid (saturation=high)',
      ja: '@nは鮮やか（彩度=高）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sk%C4%ABm%C3%B4',
      token: 'skim',
    },
    dull: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is dull (saturation=low)',
      ja: '@nは鈍い（低彩度を呈する）',
      idiom: ['little', 'vivid'],
    },
    gray: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is gray (saturation=lowest)',
      ja: '@nは無彩色を呈する（彩度=最低）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gr%C4%93waz',
      token: 'crev',
      idiom: ['least', 'vivid'],
    },
    bright: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is bright (brightness=high)',
      ja: '@nは明るい（明度=高）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/berhtaz',
      token: 'bert',
    },
    dark: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is dark (brightness=low)',
      ja: '@nは暗い（明度=低）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/dimmaz',
      idiom: ['little', 'bright'],
      token: 'dim',
    },
    white: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is white (brightness=highest)',
      ja: '@nは白い（最高明度を呈する）',
      idiom: ['most', 'bright'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hw%C4%ABtaz',
      token: 'xuit',
    },
    black: {
      d: '2024-04-26',
      c: Klass.Verb,
      en: '@n is black (brightness=lowest)',
      ja: '@nは黑い（明度=最低）',
      idiom: ['least', 'white'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/swartaz',
      token: 'suat',
    },

    // celestial
    sun: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is fixed sun (star)',
      ja: '@nは恆星（太陽）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sunn%C7%AD',
      token: 'sun',
    },
    earth: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is planet (earth)',
      ja: '@nは惑星（地球）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/er%C3%BE%C5%8D',
      token: 'hert',
    },
    moon: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is satellite (moon)',
      ja: '@nは衞星（月）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/m%C4%93n%C3%B4',
      token: 'men',
    },

    year: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n is year of @a (earth)',
      ja: '@nは@a（惑星）の年（公轉周期）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/j%C4%93r%C4%85',
      token: 'jer',
    },
    season: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n is season of @a (earth)',
      ja: '@nは@a（惑星）の季節',
      complex: ['part', 'year'],
    },
    winter: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n is winter (coldest interval) of @a (earth)',
      ja: '@nは@a（惑星）の冬（最も寒い季節）',
      complex: ['season', 'little'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wintruz',
      token: 'vint',
    },
    spring: {
      d: '2024-11-21',
      c: Klass.Verb,
      en: '@n is spring (warming interval) of @a (earth)',
      ja: '@nは@a（惑星）の春（暖まる季節）',
      complex: ['season', 'up'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wazr%C4%85',
      token: 'vazar',
    },
    summer: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n is summer (hottest interval) of @a (earth)',
      ja: '@nは@a（惑星）の夏（最も暑い季節）',
      complex: ['season', 'much'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sumaraz',
      token: 'sumar',
    },
    autumn: {
      d: '2024-11-21',
      c: Klass.Verb,
      en: '@n is autumn (cooling interval) of @a (earth)',
      ja: '@nは@a（惑星）の秋（冷える季節）',
      complex: ['season', 'down'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/harbistaz',
      token: 'karbis',
    },

    day: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is day of @a (earth)',
      ja: '@nは@a（惑星）の日（自轉周期）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/t%C4%ABnaz',
      token: 'tin',
    },
    morning: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is morning (daytime) of @a (earth)',
      ja: '@nは@a（惑星）の晝',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/murginaz',
      complex: ['part', 'day', 'bright'],
      token: 'murk',
    },
    night: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is night (evening) of @a (earth)',
      ja: '@nは@a（惑星）の夜',
      complex: ['part', 'day', 'dark'],
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/nahts',
      token: 'nat',
    },

    land: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is land (island)',
      ja: '@nは陸地 (島)',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/land%C4%85',
      token: 'lant',
    },
    sea: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a sea (lake)',
      ja: '@nは海 (湖)',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mari',
      token: 'mar',
    },
    hill: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a mountain (hill)',
      ja: '@nは山（丘）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bergaz',
      token: 'berx',
    },
    river: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is river',
      ja: '@nは河川',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/straumaz',
      token: 'stom',
    },
    sky: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is sky (atmosphere)',
      ja: '@nは空（大氣）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skiwj%C4%85',
      token: 'skiv',
    },

    cloud: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is cloud',
      ja: '@nは雲',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wulkn%C4%85',
      token: 'volk',
    },
    fog: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is fog (mist)',
      ja: '@nは霧',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mihstaz',
      token: 'mist',
    },
    rain: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is rain',
      ja: '@nは雨',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/regn%C4%85',
      token: 'ren',
    },
    snow: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is snow',
      ja: '@nは雪',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sn%C4%ABwan%C4%85',
      token: 'snev',
    },
    hail: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is hail',
      ja: '@nは雹',
      o: 'https://en.wiktionary.org/wiki/h%C3%A6gl#Old_English',
      token: 'hel',
    },
    thunder: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is thunder',
      ja: '@nは雷',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEunraz',
      token: 'dun',
    },

    feel: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n feeleth (senseth) @a (stimulus)',
      ja: '@nは@a（刺戟）を感ずる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Indo-European/sent-',
      token: 'sent',
    },
    hear: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n heareth @a (sound)',
      ja: '@nは@a（音）を聞く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hleum%C3%B4',
      token: 'xlev',
    },
    see: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n seeth @a (light)',
      ja: '@nは@a（光）を見る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wl%C4%ABtan%C4%85',
      token: 'vlit',
    },
    smell: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n smelleth @a (chemical substance)',
      ja: '@nは@a（化學物質）を嗅ぐ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/reukan%C4%85',
      token: 'riuk',
    },
    taste: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n taste @a (chemical substance)',
      ja: '@nは@a（化學物質）を味はふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/smak%C4%93n',
      token: 'smak',
    },
    touch: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n palpeth @a (pressure)',
      ja: '@nは@a（力）を觸覺する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/t%C4%93kan%C4%85',
      token: 'tek',
    },
    hurt: {
      d: '2025-03-01',
      c: Klass.Verb,
      en: '@n hurteth (feeleth pain) from @a',
      ja: '@nは@a（力）に痛む',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sairaz',
      token: 'ser',
    },

    differ: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n differeth (varieth) from @a',
      ja: '@nは@aと異なる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skiljan%C4%85',
      token: 'skil',
    },
    same: {
      d: '2024-08-27',
      c: Klass.Verb,
      en: '@n is (the same as, identical to, equal to) @a',
      ja: '@nは@aに等しい',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/samaz',
      idiom: ['least', 'differ'],
      token: 'sam',
    },
    simulate: {
      d: '2024-08-27',
      c: Klass.Verb,
      en: '@n simulateth (mimiceth, imitateth, mocketh, faketh) @a',
      ja: '@nは@aを模倣する（擬裝する）ｓ',
      o: 'https://en.wiktionary.org/wiki/mock#English',
      token: 'mok',
    },
    test: {
      d: '2024-07-26',
      c: Klass.Verb,
      en: '@n checketh (examineth, inspecteth) @a',
      ja: '@nは@aを確認する（檢査する、精査する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/keusan%C4%85',
      token: 'xus',
    },
    compare: {
      d: '2024-07-26',
      c: Klass.Verb,
      en: '@n compares @a',
      complex: ['differ', 'test'],
    },

    live: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n liveth (is alive)',
      ja: '@nは生く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/libjan%C4%85',
      token: 'lip',
    },
    die: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n (dieth, is dead)',
      ja: '@nは死ぬ',
      idiom: ['down', 'live'],
    },
    kill: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n kills @a',
      ja: '@nは殺す',
      idiom: ['done', 'because', 'die'],
    },
    wake: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n waketh (is awake)',
      ja: '@nは起きる（覺める）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wakan%C4%85',
      token: 'vax',
    },
    sleep: {
      d: '2024-04-26',
      c: Klass.Verb,
      en: '@n sleepeth (is asleep)',
      ja: '@nは眠る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/swefan%C4%85',
      idiom: ['least', 'wake'],
      token: 'suif',
    },

    lie: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n lieth (horizontally stays) on @a',
      ja: '@nは@aに寢る（臥す）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ligjan%C4%85',
      token: 'lik',
    },
    sit: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n siteth on @a',
      ja: '@nは@aに座る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sitjan%C4%85',
      token: 'sit',
    },
    stand: {
      d: '2024-08-30',
      c: Klass.Verb,
      en: '@n standeth on @a',
      ja: '@nは@aに立つ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/st%C4%81n%C4%85',
      token: 'stan',
    },
    walk: {
      d: '2024-06-18',
      c: Klass.Verb,
      en: '@n walketh on @a (ground)',
      ja: '@nは@aを步く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/walkan%C4%85',
      token: 'valk',
    },
    run: {
      d: '2024-06-18',
      c: Klass.Verb,
      en: '@n runeth on @a (ground)',
      ja: '@nは@aを走る（驅ける）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/rinnan%C4%85',
      token: 'rin',
    },
    leap: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n jumpeth (leapeth, skipeth, hopeth) over @a',
      ja: '@nは@aを跳躍する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gumb%C5%8Dn%C4%85',
      token: 'cum',
    },
    swim: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n (swimeth, flieth) in @a (fluid)',
      ja: '@nは@a（流體）を飛翔する（泳ぐ）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/swimman%C4%85',
      token: 'suim',
    },
    fly: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n flieth in @a',
      ja: '@nは@aを飛翔する（泳ぐ）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fleugan%C4%85',
      token: 'fluk',
      complex: ['swim', 'gas'],
    },

    eat: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n eateth @a (food)',
      ja: '@nは@a（食料）を食ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/etan',
      token: 'et',
    },
    bite: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n biteth @a',
      ja: '@nは@aを嚙む',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/b%C4%ABtan%C4%85',
      token: 'bit',
    },
    chew: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n cheweth @a',
      ja: '@nは@aを咀嚼する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kewwan%C4%85',
      token: 'xev',
    },
    swallow: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n swalloweth @a',
      ja: '@nは@aを嚥下する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/swelgan%C4%85',
      token: 'suil',
    },
    digest: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n digesteth @a',
      ja: '@nは@aを消化する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/meltan%C4%85',
      token: 'melt',
    },
    vomit: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n vomiteth @a',
      ja: '@nは@aを嘔吐する',
      o: 'https://en.wiktionary.org/wiki/puke',
      complex: ['back', 'eat'],
      token: 'puk',
    },
    shit: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n shiteth (urinateth) @a',
      ja: '@nは@a（糞尿）を排泄する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/drit%C4%85',
      complex: ['counter', 'eat'],
      token: 'drit',
    },

    fuck: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n fucketh @a',
      ja: '@nは@aと性交する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fukk%C5%8Dn%C4%85',
      token: 'fok',
    },
    sick: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is sick (malfunctioneth)',
      ja: '@nは病む（故障する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/seukaz',
      token: 'suk',
    },
    healthy: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n is healthy',
      ja: '@nは健康',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sundaz',
      idiom: ['little', 'sick'],
      token: 'sunt',
    },
    recover: {
      d: '2024-12-24',
      c: Klass.Verb,
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sundaz',
      en: '@n recovers',
      ja: '@nは恢復する',
      idiom: ['down', 'sick'],
    },

    emotion: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n feeleth @a (emotion)',
      ja: '@nは@a（感情）を持つ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hugiz',
      token: 'huk',
    },
    bad: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n disliketh (feeleth bad about) @a',
      ja: '@nは@aを厭ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ubilaz',
      token: 'up',
    },
    good: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n liketh (feeleth good about) @a',
      ja: '@nは@aを好む',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/g%C5%8Ddaz',
      idiom: ['little', 'bad'],
      token: 'cot',
    },
    sad: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n is (sad, depressed) about @a',
      ja: '@nは@aを悲しむ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/surg%C5%8D',
      token: 'surk',
    },
    glad: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n is (happy, glad, merry) about @a',
      ja: '@nは@aを喜ぶ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/frawaz',
      token: 'frav',
      idiom: ['little', 'sad'],
    },
    care: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n regardeth (careth about) @n',
      ja: '@nは@aを氣に掛ける',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kar%C5%8D',
      token: 'kar',
    },
    fear: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n worries (feareth, is afraid of) @a',
      ja: '@nは@aを恐れる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/furhtaz',
      complex: ['care', 'bad'],
      token: 'fort',
    },
    respect: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n respecteth (honoureth) @a',
      ja: '@nは@aを敬ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wer%C3%BEaz',
      complex: ['care', 'good'],
      token: 'vert',
    },
    neglect: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n neglecteth (is indifferent to) @a',
      ja: '@nは@aを無視する（に無關心）',
      idiom: ['little', 'care'],
    },
    serene: {
      d: '2024-09-10',
      c: Klass.Verb,
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/r%C5%8D%C5%8D',
      en: '@n is calm (serene) about @a',
      ja: '@nは@aに平穩（冷静）',
      complex: ['neglect', 'good'],
      token: 'rov',
    },
    scorn: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n scorneth (disdaineth, disrespecteth) @a',
      ja: '@nは@aを侮る（軽蔑する、見くびる）',
      complex: ['neglect', 'bad'],
    },
    hate: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n is hateth (detesteth) @a',
      ja: '@nは@aを憎惡する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hataz',
      token: 'xat',
    },
    angry: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n is angry with (mad at) @a',
      ja: '@nは@aに怒る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wrai%C3%BEaz',
      token: 'vret',
    },
    expect: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n expecteth (used to) @a',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/w%C4%81nijan',
      token: 'van',
    },
    amaze: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n is surprised (amazed) at @a',
      ja: '@nは@aに驚く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wundr%C4%85',
      token: 'von',
      idiom: ['little', 'expect'],
    },
    bore: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n is bored with @a',
      ja: '@nは@aに飽きる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bur%C5%8Dn%C4%85',
      token: 'bur',
      idiom: ['most', 'expect'],
    },
    enjoy: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n enjoyeth @a',
      ja: '@nは@aを樂しむ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/neutan%C4%85',
      token: 'niut',
    },
    trust: {
      d: '2024-08-02',
      c: Klass.Verb,
      en: '@n trusteth @a',
      ja: '@nは@aを信ずる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/tr%C5%ABw%C4%81n%C4%85',
      token: 'trov',
    },
    doubt: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n doubteth @a',
      ja: '@nは@aを疑ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/tw%C4%ABflaz',
      idiom: ['little', 'trust'],
    },
    pride: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n is proud of @a',
      ja: '@nは@aを誇る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stultaz',
      token: 'stut',
    },
    shame: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@nは@aを恥づ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skam%C5%8D',
      idiom: ['little', 'pride'],
      token: 'skam',
    },
    shun: {
      d: '2024-09-27',
      c: Klass.Verb,
      en: '@n is shuneth (avoideth) @a',
      ja: '@nは@aを避く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skeuhaz',
      token: 'skuk',
    },
    want: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n wanteth @a',
      ja: '@nは@aを求む',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wiljan%C4%85',
      idiom: ['little', 'shun'],
      token: 'vil',
    },
    love: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n loveth (is romantically attracted to) @a',
      ja: '@nは@aを愛する（を戀ふ）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gernaz',
      token: 'jern',
    },
    randy: {
      d: '2024-09-12',
      c: Klass.Verb,
      en: '@n is randy (aroused, lustful, horny, sexual) for @a',
      ja: '@nは@aに欲情する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gailaz',
      token: 'cel',
    },
    envy: {
      d: '2024-09-12',
      c: Klass.Verb,
      en: '@n envieth @a',
      ja: '@nは@aを羨む（妬む）',
      o: 'https://en.wiktionary.org/wiki/zelo#Latin',
      token: 'zel',
    },
    pity: {
      d: '2024-09-10',
      c: Klass.Verb,
      en: '@n (pitieth, feel sympathy) @a',
      ja: '@nは@aを憐れむ（に同情する）',
      o: 'https://en.wiktionary.org/wiki/natha#Old_Dutch',
      token: 'net',
    },

    laugh: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n laugheth',
      ja: '@nは笑ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hlahjan%C4%85',
      token: 'lah',
    },
    smile: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n smileth',
      ja: '@nは笑む',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sm%C4%ABlijan%C4%85',
      token: 'smil',
    },
    frown: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n frowneth',
      ja: '@nは顰む',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skelhaz',
      token: 'skel',
    },
    weep: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n weepeth @a (tear)',
      ja: '@nは@a（涙）を泣く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/w%C5%8Dpijan%C4%85',
      token: 'vop',
    },
    yell: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n yelleth (crieth, shouteth) @a (voice)',
      ja: '@nは@a（聲）を叫ぶ（鳴く）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stun%C5%8Dn%C4%85',
      token: 'stun',
    },

    know: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n knoweth @a (fact, existence)',
      ja: '@nは@a（事象、存在）を知る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/witan%C4%85',
      token: 'vit',
    },
    learn: {
      d: '2024-08-01',
      c: Klass.Verb,
      en: '@n learneth @a',
      ja: '@nは@aを學ぶ',
      idiom: ['up', 'know'],
    },
    forget: {
      d: '2024-08-01',
      c: Klass.Verb,
      en: '@n forgeteth @a',
      ja: '@nは@aを忘る',
      idiom: ['down', 'know'],
    },
    think: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n thinketh @a',
      ja: '@nは@aを考ふ（思ふ）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEankijan%C4%85',
      token: 'dank',
    },
    imagine: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n imagineth @a',
      ja: '@nは@aを想像する（夢想する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/bili%C3%BE%C5%8Dn',
      token: 'bilt',
    },
    reason: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n reasoneth @a',
      ja: '@nは@aを判ずる（推論する、理性に照らす）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ra%C3%BEj%C7%AD',
      token: 'rat',
    },
    dream: {
      d: '2024-10-16',
      c: Klass.Verb,
      en: '@n dreameth @a',
      ja: '@nは@aを夢見る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/draumaz',
      token: 'drom',
    },

    name: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n meaneth (signifieth, is a name of) @a',
      ja: '@nは@aを意味する（の名である）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/nam%C3%B4',
      token: 'nam',
    },
    speak: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n speaketh in @a (language, protocol)',
      ja: '@nは@a（言語、規約）で話す（交信する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/tal%C5%8D',
      token: 'tal',
    },
    say: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n sayeth (encodeth) @a (expression)',
      ja: '@nはを@a（表現）を言ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sagjan%C4%85',
      token: 'sak',
    },
    understand: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n understandeth (decodeth) @a (expression)',
      ja: '@nはを@a（表現）を理解する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hlustiz',
      complex: ['counter', 'say'],
      token: 'xlus',
    },
    write: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n writeth @a (expression)',
      ja: '@nはを@a（表現）を書く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wr%C4%ABtan%C4%85',
      token: 'vrit',
    },
    read: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n readeth @a (expression)',
      ja: '@nはを@a（表現）を讀む',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/r%C4%93dan%C4%85',
      complex: ['counter', 'write'],
      token: 'ret',
    },
    ask: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n asketh @a (question) to @d',
      ja: '@nはを@a（質問）を@dへ問ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fr%C4%93g%C5%8D',
      token: 'frex',
    },
    answer: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n answereth @a to @d',
      ja: '@nはを@aを@dへ答ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/swar%C5%8Dn%C4%85',
      complex: ['counter', 'ask'],
      token: 'suir',
    },

    greet: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n greeteth to @a',
      ja: '@nは@aへ挨拶する',
      o: 'https://en.wiktionary.org/wiki/salus#Latin',
      token: 'sal',
    },
    forgive: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n forgiveth @a',
      ja: '@nは@aを許す',
      o: 'https://en.wiktionary.org/wiki/donare#Latin',
      token: 'don',
    },
    thank: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n thanketh @a',
      ja: '@nは@aに感謝する',
      o: 'https://en.wiktionary.org/wiki/gratus#Latin',
      token: 'crat',
    },
    promise: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n promiseth (guaranteeth, voweth) @a',
      ja: '@nは@aを約束する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/haitan%C4%85',
      token: 'ket',
    },
    command: {
      d: '2024-09-29',
      c: Klass.Verb,
      en: '@n commandeth (requesteth, recommendeth) @a',
      ja: '@nは@aを命令する（要求する、推奬する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stiurijan%C4%85',
      token: 'stur',
    },

    sing: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n singeth (playeth) @a (music, song)',
      ja: '@nは@a（歌、曲）を歌ふ（演奏する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/singwan%C4%85',
      token: 'sink',
    },
    dance: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n danceth @a (choreography)',
      ja: '@nは@a（振り付け）を踊る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/%C3%BEans%C5%8Dn',
      token: 'dans',
    },

    rot: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n roteth',
      ja: '@nは腐敗する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/rut%C4%81n%C4%85',
      token: 'rut',
    },
    fresh: {
      d: '2024-07-24',
      c: Klass.Verb,
      en: '@n is fresh',
      ja: '@nは新鮮',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/friskaz',
      idiom: ['little', 'rot'],
      token: 'frix',
    },

    beget: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n beareth (begeteth, reproducteth, is a parent of) @a (child)',
      ja: '@nは生殖する（@aを生む、@aの親である）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/burdiz',
      token: 'burt',
    },
    man: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is male (produceth sperms)',
      ja: '@nは@a（精巢、雄蕊）を持つ（男）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gum%C3%B4',
      token: 'jum',
    },
    woman: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is female (produceth ova)',
      ja: '@nは@a（卵巢、雌蕊）を持つ（女）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/w%C4%ABb%C4%85',
      token: 'vip',
    },

    sibling: {
      d: '2025-02-08',
      c: Klass.Verb,
      en: '@n is a sibiling of (shareth a parent with) @a',
      ja: '@nは@aの同胞（と親を共有する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sibjaz',
      complex: ['done', 'beget', 'same'],
      token: 'sip',
    },
    family: {
      d: '2025-02-08',
      c: Klass.Verb,
      en: '@n is in blood relation with @a',
      ja: '@nは@aの血族',
      etymology:
        'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kunj%C4%85',
      token: 'xun',
    },

    mammal: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a mammal',
      ja: '@nは哺乳類',
      o: 'https://en.wiktionary.org/wiki/mammalis',
      token: 'mamal',
    },
    human: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a human (homo)',
      ja: '@nは人屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mann-',
      token: 'man',
    },
    rat: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a rodents (rat, mouse)',
      ja: '@nは齧歯目（鼠）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/m%C5%ABs',
      token: 'mus',
    },
    hare: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a lagomorpha (hare, rabbit)',
      ja: '@nは兔形目（兔）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/has%C3%B4',
      token: 'xas',
    },
    cat: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a felis (cat)',
      ja: '@nは貓屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kattuz',
      token: 'kat',
    },
    fox: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a vulpes (fox)',
      ja: '@nは狐屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fuhsaz',
      token: 'fus',
    },
    dog: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a canis (dog)',
      ja: '@nは犬屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hundaz',
      token: 'hunt',
    },
    wolf: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a canis lupus (wolf)',
      ja: '@nは狼',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wulfaz',
      token: 'volf',
    },
    bear: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a bear',
      ja: '@nは熊科',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ber%C3%B4',
      token: 'ber',
    },
    sheep: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is an ovis (sheep)',
      ja: '@nは羊屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sk%C4%93p%C4%85',
      token: 'skep',
    },
    goat: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a capra (goat)',
      ja: '@nは山羊屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/gaits',
      token: 'cet',
    },
    deer: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a deer',
      ja: '@nは鹿科',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/raih%C3%B4',
      token: 'reh',
    },
    horse: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a equus (horse)',
      ja: '@nは馬屬',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hruss%C4%85',
      token: 'rus',
    },
    cow: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a bovin (cow)',
      ja: '@nは牛族',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/k%C5%ABz',
      token: 'kov',
    },
    pig: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a sus (pig, hog)',
      ja: '@nは猪屬（豚）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sw%C4%ABn%C4%85',
      token: 'suin',
    },

    reptile: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a reptile',
      ja: '@nは爬虫類',
      o: 'https://en.wiktionary.org/wiki/reptilis#Latin',
      token: 'reptil',
    },
    snake: {
      d: '2024-07-15',
      c: Klass.Verb,
      en: '@n is a serpentis (snake)',
      ja: '@nは蛇亞目',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/snegan%C4%85',
      token: 'snek',
    },

    bird: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is an avis (bird)',
      ja: '@nは鳥類',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fuglaz',
      token: 'folk',
    },
    crow: {
      d: '2024-07-15',
      c: Klass.Verb,
      en: '@n is a corvida (crow, raven)',
      ja: '@nは烏科',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hrabnaz',
      token: 'rap',
    },

    fish: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a fish',
      ja: '@nは魚類',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fiskaz',
      token: 'fisk',
    },

    amphibia: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a amphibia',
      ja: '@nは兩棲類',
      o: 'https://en.wiktionary.org/wiki/amphibius#Latin',
      token: 'anfip',
    },
    frog: {
      d: '2024-07-15',
      c: Klass.Verb,
      en: '@n is an anura (frog)',
      ja: '@nは無尾目（蛙）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fruskaz',
      token: 'fruk',
    },

    plant: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is a plant',
      ja: '@nは植物',
      o: 'https://en.wiktionary.org/wiki/planta#Latin',
      token: 'plant',
    },
    tree: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n is a tree',
      ja: '@nは木本植物',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bagmaz',
      token: 'bam',
    },

    body: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a body',
      ja: '@nは肉體',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hrefaz',
      token: 'ref',
    },
    bone: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a bone',
      ja: '@nは骨',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bain%C4%85',
      token: 'ben',
    },
    spine: {
      d: '2025-02-06',
      c: Klass.Verb,
      en: '@n is a spine',
      ja: '@nは脊椎',
      o: 'https://en.wiktionary.org/wiki/spina#Latin',
      token: 'spin',
    },
    flesh: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is flesh (meat, muscle)',
      ja: '@nは筋肉',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/flaiski',
      token: 'fles',
    },
    fat: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is body fat',
      ja: '@nは體脂肪',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/faitaz',
      token: 'fet',
    },
    skin: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a skin (peel)',
      ja: '@nは皮膚（皮革）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/skin%C3%BE%C4%85',
      token: 'skin',
    },
    head: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a head',
      ja: '@nは頭',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/haubud%C4%85',
      token: 'hot',
    },
    neck: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a neck',
      ja: '@nは首',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hnakk%C3%B4',
      token: 'nak',
    },
    shoulder: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a shoulder (buttock)',
      ja: '@nは肩（尻）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/skuldru',
      token: 'xult',
    },
    limb: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a limb (leg, arm, branch)',
      ja: '@nは肢（腕、脚、枝）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/limuz',
      token: 'lim',
    },
    arm: {
      d: '2024-11-24',
      c: Klass.Verb,
      en: '@n is an arm',
      ja: '@nは腕',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/armaz',
      token: 'harm',
    },
    leg: {
      d: '2024-11-24',
      c: Klass.Verb,
      en: '@n is a leg',
      ja: '@nは肢（腕、脚）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/lagjaz',
      token: 'lak',
    },
    //extremity: { d: '2024-02-13', c: Klass.Verb, token: 'hand', o: 'https://en.wiktionary.org/wiki/reconstruction:proto-germanic/handuz', en: '@0 is a (extremity, hand, foot) of @1' },
    foot: {
      d: '2024-11-24',
      c: Klass.Verb,
      en: '@n is a foot',
      ja: '@nは足',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/f%C5%8Dts',
      token: 'fot',
    },
    hand: {
      d: '2024-11-24',
      c: Klass.Verb,
      en: '@n is a hand',
      ja: '@nは手',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mund%C5%8D',
      token: 'munt',
    },
    trunk: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a trunk (torso, stem)',
      ja: '@nは胴（幹、莖）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stamniz',
      token: 'stam',
    },
    breast: {
      d: '2024-09-22',
      c: Klass.Verb,
      en: '@n is a chest (breast)',
      ja: '@nは胸',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/brusts',
      token: 'brus',
    },
    belly: {
      d: '2024-09-22',
      c: Klass.Verb,
      en: '@n is a belly',
      ja: '@nは腹',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kwe%C3%BEuz',
      token: 'kuit',
    },
    tail: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a tail',
      ja: '@nは尾',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stertaz',
      token: 'stet',
    },
    hair: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a hair (fur)',
      ja: '@nは毛',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hazdaz',
      token: 'has',
    },
    horn: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a horn',
      ja: '@nは角',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hurn%C4%85',
      token: 'hurn',
    },
    tooth: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a tooth (fang)',
      ja: '@nは齒牙',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/tan%C3%BEs',
      token: 'tan',
    },
    nail: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a nail (claw)',
      ja: '@nは爪',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/naglaz',
      token: 'nel',
    },
    eye: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is an eye',
      ja: '@nは目',
      o: 'https://en.wiktionary.org/wiki/%DA%86%D8%B4%D9%85#Persian',
      token: 'txam',
    },
    ear: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is an ear',
      ja: '@nは耳',
      o: 'https://en.wiktionary.org/wiki/%DA%AF%D9%88%D8%B4#Persian',
      token: 'cox',
    },
    nose: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a nose',
      ja: '@nは鼻',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/nas%C5%8D',
      token: 'nas',
    },
    mouth: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a mouth',
      ja: '@nは口',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mun%C3%BEaz',
      token: 'mun',
    },
    lip: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a lip',
      ja: '@nは脣',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/lep%C3%B4',
      token: 'lep',
    },
    tongue: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a tongue',
      ja: '@nは舌',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/tung%C7%AD',
      token: 'tunk',
    },

    viscera: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a viscera (inner organ)',
      ja: '@nは内臓',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/%C3%BEarmaz',
      token: 'darm',
    },
    lung: {
      d: '2024-09-02',
      c: Klass.Verb,
      en: '@n is a lung',
      ja: '@nは肺',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/lung%C3%B4',
      token: 'lunk',
    },
    heart: {
      d: '2024-09-02',
      c: Klass.Verb,
      en: '@n is a heart',
      ja: '@nは心臟',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hert%C3%B4',
      token: 'xert',
    },
    maw: {
      d: '2024-09-02',
      c: Klass.Verb,
      en: '@n is a maw (stomach)',
      ja: '@nは胃',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mag%C3%B4',
      token: 'mav',
    },
    liver: {
      d: '2024-09-02',
      c: Klass.Verb,
      en: '@n is a liver',
      ja: '@nは肝臓',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/libr%C5%8D',
      token: 'liur',
    },
    womb: {
      d: '2024-09-22',
      c: Klass.Verb,
      en: '@n is a prostate (womb)',
      ja: '@nは前立腺（子宮）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wamb%C5%8D',
      token: 'vam',
    },
    vagina: {
      d: '2024-09-22',
      c: Klass.Verb,
      en: '@n is a vagina',
      ja: '@nは膣',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fu%C3%BEiz',
      token: 'fut',
    },
    penis: {
      d: '2024-09-22',
      c: Klass.Verb,
      en: '@n is a penis (clitoris)',
      ja: '@nは陰莖（陰核）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/pinti',
      token: 'pint',
    },

    egg: {
      d: '2024-09-16',
      c: Klass.Verb,
      en: '@n is an egg (ovum)',
      ja: '@nは卵（卵子）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ajj%C4%85',
      token: 'aj',
    },

    blood: {
      d: '2024-07-29',
      c: Klass.Verb,
      en: '@n is blood',
      ja: '@nは血',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bl%C5%8D%C3%BE%C4%85',
      token: 'blot',
    },
    milk: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n is milk',
      ja: '@nは乳',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/meluks',
      token: 'melk',
    },
    lymph: {
      d: '2024-08-31',
      c: Klass.Verb,
      en: '@n is lymph',
      ja: '@nはlymph',
      o: 'https://en.wiktionary.org/wiki/%CE%BD%CF%8D%CE%BC%CF%86%CE%B7#Ancient_Greek',
      token: 'ninf',
    },

    flower: {
      d: '2024-09-02',
      c: Klass.Verb,
      en: '@n is a flower (bloom, blossom)',
      ja: '@nは花',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/bl%C5%8Dan%C4%85',
      token: 'blok',
    },
    leaf: {
      d: '2024-09-02',
      c: Klass.Verb,
      en: '@n is a leaf',
      ja: '@nは葉',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/laub%C4%85',
      token: 'lop',
    },
    root: {
      d: '2024-09-02',
      c: Klass.Verb,
      en: '@n is a root',
      ja: '@nは根',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wr%C5%8Dts',
      token: 'vrot',
    },

    person: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n is a person (an individual, a citizen)',
      ja: '@nは人間（個人、市民、）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/liudiz',
      token: 'liut',
    },
    nation: {
      d: '2024-08-24',
      c: Klass.Verb,
      en: '@n is a country (nation)',
      ja: '@nは國家',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/mark%C5%8D',
      token: 'mark',
    },
    rule: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n ruleth (ordereth, dictateth) @a',
      ja: '@nは@aを統治する（支配する）',
      o: 'https://en.wiktionary.org/wiki/rego#Latin',
      token: 'rex',
    },

    noble: {
      d: '2024-10-01',
      c: Klass.Verb,
      en: '@n is privileged',
      ja: '@nは特權を持つ（貴族）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/r%C4%ABkijaz',
      token: 'rik',
    },

    work: {
      d: '2024-02-13',
      c: Klass.Verb,
      en: '@n worketh (laboureth)',
      ja: '@nは勞働する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/werk%C4%85',
      token: 'verk',
    },
    dwell: {
      d: '2024-12-20',
      c: Klass.Verb,
      en: '@n dwelleth in @a (house)',
      ja: '@nは@a（家）に居住する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/b%C5%8D%C3%BE%C5%8D',
      token: 'bot',
    },
    use: {
      d: '2024-06-14',
      c: Klass.Verb,
      en: '@n useth @a (tool, instrument)',
      ja: '@nは@a（道具）を使ふ',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/nut%C5%8D',
      token: 'nut',
    },
    help: {
      d: '2024-06-18',
      c: Klass.Verb,
      en: '@n helpeth (assisteth) @a',
      ja: '@nは@aを助ける（支援する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/helpan%C4%85',
      token: 'help',
    },
    harm: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n harmeth (hurteth, damageth) @a',
      ja: '@nは@aを害する（傷附ける）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/ska%C3%BE%C3%B4',
      token: 'skat',
    },

    wont: {
      d: '2024-09-01',
      c: Klass.Verb,
      en: '@n is used to @a (custom, habit, routine)',
      ja: '@nは@a（習慣）に慣れる',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wun%C4%81n%C4%85',
      token: 'vont',
    },
    lead: {
      d: '2024-09-01',
      c: Klass.Verb,
      en: '@n leadeth @a',
      ja: '@nは@aを導く',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/dragan%C4%85',
      token: 'drak',
    },

    stab: {
      d: '2024-11-24',
      c: Klass.Verb,
      en: '@n stabeth @a',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stubbaz',
      token: 'stup',
    },
    cut: {
      d: '2024-11-21',
      c: Klass.Verb,
      en: '@n cuteth @a',
      ja: '@nは@aを切る（斷つ）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sn%C4%AB%C3%BEan%C4%85',
      token: 'snet',
    },
    pick: {
      d: '2024-09-09',
      c: Klass.Verb,
      en: '@n picketh (hunteth, gathereth, collects) @a (harvest, prey)',
      ja: '@nは@aを拾ふ（狩る、収穫する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/jakk%C5%8Dn%C4%85',
      token: 'jak',
    },
    lick: {
      d: '2024-08-19',
      c: Klass.Verb,
      en: '@n licketh @a',
      ja: '@nは@aを舐める',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/likk%C5%8Dn%C4%85',
      complex: ['tongue', 'touch'],
      token: 'lix',
    },
    kiss: {
      d: '2024-11-23',
      c: Klass.Verb,
      en: '@nは@aに接吻する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kussaz',
      complex: ['lip', 'touch'],
      token: 'kus',
    },
    caress: {
      d: '2024-11-23',
      c: Klass.Verb,
      en: '@n carreseth @a',
      ja: '@nは@aを撫でる（愛撫する）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/streukan%C4%85',
      token: 'stuk',
    },
    hug: {
      d: '2024-11-23',
      c: Klass.Verb,
      en: '@n hugeth @a',
      ja: '@nは@aを抱擁する',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fa%C3%BEmaz',
      token: 'fam',
    },
    hit: {
      d: '2024-11-23',
      c: Klass.Verb,
      en: '@n hiteth (kicketh, puncheth) @a',
      ja: '@nは@aを打つ（毆る、蹴る）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hittijan%C4%85',
      token: 'hit',
    },
    kick: {
      d: '2024-11-23',
      c: Klass.Verb,
      en: '@n kicketh @a',
      ja: '@nは@aを蹴る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/spurnan%C4%85',
      complex: ['foot', 'hit'],
      token: 'spun',
    },
    punch: {
      d: '2024-11-23',
      c: Klass.Verb,
      en: '@n puncheth @a',
      ja: '@nは@aを毆る',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/slahan%C4%85',
      complex: ['hand', 'hit'],
      token: 'slak',
    },

    rope: {
      d: '2025-02-08',
      c: Klass.Verb,
      en: '@n is a rope {cord, string}',
      ja: '@nは紐（繩、糸）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/taug%C5%8D',
      token: 'tok',
    },
    knife: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@nは刃（劍、刀）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sahs%C4%85',
      complex: ['cut', 'done', 'use'],
      token: 'saks',
    },
    scissor: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n is a pair of scissors',
      ja: '@nは鋏',
      complex: ['two', 'knife'],
    },
    spear: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n is a spear (pin, skewer)',
      ja: '@nは槍（鋲、串）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/speru',
      token: 'sper',
    },
    rod: {
      d: '2024-07-28',
      c: Klass.Verb,
      en: '@n is a rod (stuff, wand, club)',
      ja: '@nは棒（杖、棍）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/stikk%C3%B4',
      token: 'stik',
    },
    dish: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is a dish (bowl, cup, container)',
      ja: '@nは器（皿、碗、盆、杯、壺、瓶、罐）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/hnappaz',
      token: 'knap',
    },
    fork: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is a fork',
      ja: '@nは叉',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Celtic/gabl%C4%81',
      token: 'cabal',
    },
    spoon: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is a spoon (scoop)',
      ja: '@nは匙',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/sp%C4%93nuz',
      token: 'spen',
    },
    tong: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is a tong (plier, chopstick)',
      ja: '@nは箸（鉗子）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/tang%C5%8D',
      token: 'tank',
    },
    money: {
      d: '2024-08-25',
      c: Klass.Verb,
      en: '@n is (money, coin, bill)',
      ja: '@nは金（貨幣、紙幣、硬貨）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/fehu',
      token: 'fex',
    },
    ship: {
      d: '2024-10-05',
      c: Klass.Verb,
      en: '@n is a ship (boat)',
      ja: '@nは舟',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/baitaz',
      token: 'bet',
    },
    bridge: {
      d: '2025-02-08',
      c: Klass.Verb,
      en: '@n is a bridge',
      ja: '@nは橋梁',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/brugj%C7%AD',
      token: 'bruk',
    },
    knot: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is a knot (tangle, tie, bond)',
      ja: '@nは結び目（絡まり）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/knutt%C3%B4',
      token: 'knut',
    },
    book: {
      d: '2025-07-19',
      c: Klass.Verb,
      en: '@n is a book (volume, tome)',
      ja: '@nは本（卷、册）',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/b%C5%8Dks',
      token: 'bok',
    },

    age: {
      d: '2024-12-07',
      c: Klass.Verb,
      en: '@n is at age of @a',
      ja: '@nは@a歳',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/alan%C4%85',
      token: 'al',
    },

    sentence: {
      d: '2024-10-05',
      c: Klass.Verb,
      en: '@n is a sentence',
      ja: '@nは文（命題）',
      o: 'https://en.wiktionary.org/wiki/%CF%86%CF%81%CE%AC%CF%83%CE%B9%CF%82#Ancient_Greek',
      token: 'fras',
    },
    clause: {
      d: '2024-10-05',
      c: Klass.Verb,
      en: '@n is a clause',
      ja: '@nは節',
      o: 'https://en.wiktionary.org/wiki/clauso#Latin',
      token: 'klos',
    },
    word: {
      d: '2024-10-05',
      c: Klass.Verb,
      en: '@n is a word',
      ja: '@n is a 單詞',
      o: 'https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/wurd%C4%85',
      token: 'vort',
    },

    verb: {
      d: '2024-10-05',
      c: Klass.Verb,
      en: '@n is a verb',
      ja: '@nは動詞',
      o: 'https://en.wiktionary.org/wiki/verbo#Latin',
      token: 'verp',
    },
    case: {
      d: '2024-10-05',
      c: Klass.Verb,
      en: '@n is a case',
      ja: '@nは格',
      o: 'https://en.wiktionary.org/wiki/casu#Latin',
      token: 'kas',
    },
    nominative: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is nominative',
      ja: '@nは主格',
      complex: ['verb', 'head'],
    },
    oblique: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is oblique',
      ja: '@nは非主格',
      complex: ['verb', 'arm'],
    },
    accusative: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is accusative',
      ja: '@nは對格',
      complex: ['verb', 'zero', 'th', 'arm'],
    },
    dative: {
      d: '2024-12-23',
      c: Klass.Verb,
      en: '@n is dative',
      ja: '@nは與格',
      complex: ['verb', 'one', 'th', 'arm'],
    },

    continent_eurasia: {
      d: '2025-02-28',
      c: Klass.Verb,
      en: '@n is the continent eurasia',
      ja: '@nは ゆうらしあ大陸',
      token: 'evras',
    },
    continent_africa: {
      d: '2025-02-28',
      c: Klass.Verb,
      en: '@n is the continent africa',
      ja: '@nは あふりか大陸',
      etymology: 'https://en.wiktionary.org/wiki/africus#Latin',
      token: 'afrik',
    },
    continent_north_america: {
      d: '2025-02-28',
      c: Klass.Verb,
      en: '@n is the continent north america',
      ja: '@nは 北あめりか大陸',
      etymology: 'https://en.wiktionary.org/wiki/australis#Latin',
      complex: ['$amrik', 'north'],
    },
    continent_australia: {
      d: '2025-02-28',
      c: Klass.Verb,
      en: '@n is the continent australia',
      ja: '@nは おうすとらりあ大陸',
      etymology: 'https://en.wiktionary.org/wiki/australis#Latin',
      token: 'auster',
    },
    continent_south_america: {
      d: '2025-02-28',
      c: Klass.Verb,
      en: '@n is the continent south america',
      ja: '@nは 南あめりか大陸',
      etymology: 'https://en.wiktionary.org/wiki/australis#Latin',
      complex: ['$amrik', 'done', 'north'],
    },

    ...Object.fromEntries(
      [
        [
          'us',
          'the united states',
          '2024-08-25',
          //'amrik',
          //'https://en.wiktionary.org/wiki/America#Latin',
        ],
        [
          'cn',
          'china',
          '2024-08-25',
          //'zjugcok',
          //'https://en.wiktionary.org/wiki/%E4%B8%AD%E5%9C%8B',
        ],
        [
          'de',
          'germany',
          '2024-08-25',
          //'devdisk',
          //'https://en.wiktionary.org/wiki/Reconstruction:Proto-West_Germanic/%C3%BEiudisk',
        ],
        [
          'jp',
          'japan',
          '2024-08-25',
          //'nitfon',
          //'https://en.wiktionary.org/wiki/%E6%97%A5%E6%9C%AC',
        ],
        [
          'in',
          'india',
          '2024-11-22',
          //'varat',
          //'https://en.wiktionary.org/wiki/%E0%A4%AD%E0%A4%BE%E0%A4%B0%E0%A4%A4#Sanskrit',
        ],
        [
          'gb',
          'the united kingdom',
          '2024-08-25',
          //'britan',
          //'https://en.wiktionary.org/wiki/Britannia#Latin',
        ],
        [
          'fr',
          'france',
          '2024-08-25',
          //'fragk',
          //'https://en.wiktionary.org/wiki/Francia#Latin',
        ],
        [
          'it',
          'italy',
          '2024-11-22',
          //'ital',
          //'https://en.wiktionary.org/wiki/Italia#Latin',
        ],
        [
          'ca',
          'canada',
          '2024-11-22',
          //'kanat',
          //'https://en.wiktionary.org/wiki/kanata#Laurentian',
        ],
        [
          'br',
          'brazil',
          '2024-11-22',
          //'brasil',
          //'https://en.wiktionary.org/wiki/Brasil#Portuguese',
        ],
        [
          'ru',
          'russia',
          '2025-02-08',
          //'rusi',
          //'https://en.wiktionary.org/wiki/%D0%A0%D1%83%D1%81%D1%8C#Old_East_Slavic',
        ],
        ['tw', 'taiwan', '2025-02-28'],
      ].map(([iso, name, date]) => [
        `nation_${iso.toLowerCase()}`,
        {
          date,
          c: Klass.Verb,
          en: `[country] @0 is ${name} (${iso})`,
          o: 'ISO 3166-1 alpha-2',
          //idiom: ['nation', 'called', '$' + acronymToWord(iso)],
          complex: ['nation', '$' + acronymToWord(iso)],
        },
      ])
    ),

    ...Object.fromEntries(
      [
        ['eng', '2024-08-31', 'english'],
        ['cmn', '2024-08-31', 'mandarin'],
        ['hin', '2024-08-31', 'hindustani (hindi, urdu) '],
        ['spa', '2024-08-31', 'spanish'],
        ['ara', '2024-08-31', 'arabic'],
        ['fra', '2024-08-31', 'french'],
        ['rus', '2024-08-31', 'russian'],
        ['deu', '2024-08-31', 'german'],
        ['jpn', '2024-08-31', 'japanese'],
      ].map(([iso, date, adjective]) => [
        `language_${iso}`,
        {
          date,
          c: Klass.Verb,
          complex: ['done', 'speak', '$' + acronymToWord(iso)],
          en: `[language] @0 is ${adjective} language (${iso})`,
        },
      ])
    ),
  }).flatMap(([k, v]) => {
    const r = [];

    const { token, o, complex, idiom, ...vRest } = v;

    r.push([k, { ...vRest, formation: Formation.Simplex, o, token }]);
    if (complex)
      r.push([
        k + '*',
        {
          ...vRest,
          ...(token ? { en: `=${token}` } : {}),
          formation: Formation.Complex,
          o: complex.join('+'),
          complex,
        },
      ]);
    if (idiom)
      r.push([
        k + '#',
        {
          ...vRest,
          ...(token ? { en: `=${token}` } : {}),
          formation: Formation.Idiom,
          o: idiom.join('␣'),
          idiom,
        },
      ]);

    return r;
  })
);

const toBetokeners = (ks: string[]) =>
  ks.map((k) =>
    k.startsWith('$')
      ? k.substring(1)
      : dicPre.get(k)?.token ??
        dicPre.get(k + '*')?.token ??
        dicPre.get(k + '#')?.token
  );

// generate
for (let i = 0; i < dicPre.size + 1; i++)
  for (const [k, v] of dicPre.entries())
    if ('complex' in v) {
      if (v.complex.some((it) => !dicPre.has(k))) dicPre.delete(k);

      const tokens = toBetokeners(v.complex);

      if (tokens.every((it) => typeof it === 'string')) {
        delete v.complex;
        dicPre.set(k, {
          ...v,
          token: tokens.reduce((acc, it) =>
            invalid(acc + it)
              ? acc + (/[aiueo]$/.test(acc) ? 'q' : 'e') + it
              : acc + it
          ),
        });
      }
    } else if ('idiom' in v) {
      if (v.idiom.some((it) => !dicPre.has(k))) dicPre.delete(k);

      const tokens = toBetokeners(v.idiom);

      if (tokens.every((it) => typeof it === 'string')) {
        delete v.idiom;
        dicPre.set(k, {
          ...v,
          token: tokens.join(' '),
        });
      }
    }

interface Value {
  d: string;
  c: string;
  en: string;
  ja?: string;
  formation: Formation;
  o: string;
  token: string;
  ipa: string;
}

const dic = dicPre as Map<string, Value>;

// delete failed
for (const k of dic.keys())
  if (dic.get(k).token)
    dic.set(k, { ...dic.get(k), ipa: toIpa(dic.get(k).token) });
  else {
    dic.delete(k);
    console.warn(`deleted .${k}`);
  }

// check homograph
const keys = [...dic.keys()];
for (let i = 0; i < dic.size; i++)
  for (let j = i + 1; j < dic.size; j++) {
    const k0: string = keys[i];
    const k1: string = keys[j];

    if (dic.get(k0)?.token === dic.get(k1)?.token)
      console.error(`homograph: [${k0}, ${k1}] = ${dic.get(k0)?.token}`);
  }

for (const [k, { token, formation }] of dic.entries()) {
  if (formation === Formation.Simplex)
    if (7 <= token.length)
      console.error(`invalid: long simplex: .${k} = ${token}`);

  if (formation !== Formation.Idiom) {
    const invalidity = invalid(token);
    if (invalidity) console.error(`invalid: ${invalidity}: .${k} = ${token}`);
  }
}

export default new Map(
  [...dic.entries()].sort(([, a], [, b]) => compare(a.token, b.token))
);

export const translate = (code: string) =>
  code
    .replace(
      /[a-z_]+/g,
      (k) =>
        dic.get(k)?.token ??
        dic.get(k + '*')?.token ??
        dic.get(k + '#')?.token ??
        k
    )
    .replace(/ -/g, '-');
